version: "3"
services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: my-app:latest
    container_name: docker-web-1
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_APP=main.py
    restart: unless-stopped